name: Build EXE (Win7 Compatible)

on:
  push:
    paths:
      - "**.py"
      - "requirements.txt"
      - ".github/workflows/build.yml"
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2019

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Cache pip
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Set up Python 3.7
      uses: actions/setup-python@v5
      with:
        python-version: "3.7"

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip install pyinstaller==4.10

    - name: Build EXE
      run: |
        pyinstaller gui_bot.py --onefile --windowed --icon=myicon.ico --name auto_bot

    - name: Upload EXE
      uses: actions/upload-artifact@v4
      with:
        name: auto-bot-exe
        path: dist/auto_bot.exe
